spring:
  application:
    name: point

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
    defer-datasource-initialization: true   # 데이터 소스 초기화 시점 지연, SQL 실행 후 JPA 엔티티 데이터베이스 스키마에 맵핑

  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    # 쿼리 파라미터
    org.hibernate.type: trace

##################################
# 포인트 정책
##################################
point:
  one-time-maximum-limit: 100000